using LanceServer.Core.Configuration;
using LanceServer.Core.SymbolTable;
using LanceServer.Parser;

namespace LanceServer.Core.Workspace
{
    public class Workspace
    {
        private Dictionary<Uri, Document> _documents = new();
        private Dictionary<string, ISymbol> _globalSymbols = new();

        private readonly SymbolTableConfiguration _config;
        
        /// <summary>
        /// Provides the interface to the parser generated by antlr
        /// </summary>
        private ParserManager _parserManager;

        public Workspace(ParserManager parserManager, SymbolTableConfiguration config)
        {
            _parserManager = parserManager;
            _config = config;
        }

        public Document GetDocumentWithUpdatedSymbolTable(Uri uri)
        {
            var document = GetDocument(uri);
            if (document.State >= DocumentState.Visited)
            {
                return document;
            }
            
            if (document.State != DocumentState.Parsed)
            {
                throw new ArgumentException();
            }

            var symbolTable = _parserManager.GetSymbolTableForDocument(document);
            foreach (var symbol in symbolTable)
            {
                AddSymbol(symbol);
            }

            return document;
        }

        /// <summary>
        /// Returns the document with a parse tree from memory or creates it.
        /// </summary>
        /// <param name="uri">The URI of the document</param>
        public Document GetDocumentWithParseTree(Uri uri)
        {
            var document = GetDocument(uri);
            if (document.State >= DocumentState.Parsed)
            {
                return document;
            }
            
            if (document.State != DocumentState.Read)
            {
                throw new ArgumentException();
            }

            document.Tree = _parserManager.Parse(document);
            return document;
        }

        /// <summary>
        /// Returns the document from memory or creates it.
        /// </summary>
        /// <param name="uri">The URI of the document</param>
        public Document GetDocument(Uri uri)
        {
            if (HasDocument(uri))
            {
                return _documents[uri];
            }

            var document = Util.ReadDocument(uri);
            _documents.Add(uri, document);
            return document;
        }

        /// <summary>
        /// Returns true if this workspace has a document with that URI.
        /// </summary>
        /// <param name="uri">The URI of the document</param>
        public bool HasDocument(Uri uri)
        {
            return _documents.ContainsKey(uri);
        }

        /// <summary>
        /// Adds the document to this workspace, returns true if successfully added or false if a document with that URI already exists.
        /// </summary>
        /// <param name="uri">The URI of the document</param>
        public bool AddDocument(Uri uri)
        {
            if (HasDocument(uri))
            {
                return false;
            }

            GetDocument(uri);
            return true;
        }

        /// <summary>
        /// Returns the symbol.
        /// </summary>
        /// <param name="symbolName">The name of the symbol</param>
        /// <param name="documentOfReference">The URI of the document where the symbol is used</param>
        public ISymbol GetSymbol(string symbolName, Uri documentOfReference)
        {
            var symbol = GetDocument(documentOfReference).GetSymbol(symbolName);

            if (symbol is not null)
            {
                return symbol;
            }
            
            symbol = _globalSymbols[symbolName];
            
            if (symbol is not null)
            {
                return symbol;
            }

            return new ErrorSymbol($"Cannot resolve symbol '{symbolName}'");
        }

        private void AddSymbol(ISymbol symbol)
        {
            if (IsGlobalSymbol(symbol.SourceDocument))
            {
                _globalSymbols.Add(symbol.Identifier, symbol);
            }
            else
            {
                GetDocument(symbol.SourceDocument).AddSymbol(symbol);
            }
        }

        private bool IsGlobalSymbol(Uri sourceDocument)
        {
            var fileEnding = Path.GetExtension(sourceDocument.AbsolutePath);

            if (_config.GlobalFileEndings.Contains(fileEnding))
            {
                return true;
            }

            var directories = Path.GetDirectoryName(sourceDocument.AbsolutePath)!.Split(Path.DirectorySeparatorChar);

            if (_config.GlobalDirectories.Intersect(directories).Any())
            {
                return true;
            }
            
            return false;
        }
    }
}