using Antlr4.Runtime.Tree;
using LanceServer.Core.Symbol;
using LanceServer.Core.Workspace;

namespace LanceServer.Parser;

/// <summary>
/// Provides the interface to the parser generated by antlr
/// </summary>
public interface IParserManager
{
    IParseTree Parse(PreprocessedDocument document);
    List<ISymbol> GetSymbolTableForDocument(ParsedDocument document);
}