using Antlr4.Runtime.Tree;
using LanceServer.Core.Symbol;
using LanceServer.Core.Workspace;

namespace LanceServer.Parser
{
    /// <summary>
    /// Provides the interface to the parser generated by antlr
    /// </summary>
    public interface IParserManager
    {
        /// <summary>
        /// Parses the provided document and returns the parse tree.
        /// </summary>
        /// <param name="document">The document to be parsed</param>
        /// <returns>The parse tree</returns>
        IParseTree Parse(PreprocessedDocument document);
    
        /// <summary>
        /// Visits the parse tree of the provided document to generate a list of all defined symbols
        /// </summary>
        /// <param name="document">The document to be visited</param>
        /// <returns>A list of all defined symbols</returns>
        IEnumerable<ISymbol> GetSymbolTableForDocument(ParsedDocument document);
    
        /// <summary>
        /// Visits the parse tree of the provided document to generate a list of all symbol uses
        /// </summary>
        /// <param name="document">The document to be visited</param>
        /// <returns>A list of all symbol uses</returns>
        IEnumerable<SymbolUse> GetSymbolUseForDocument(SymbolisedDocument document);
    }
}