//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ..\..\antlr4-grammar\SinumerikNC.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SinumerikNCParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface ISinumerikNCVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] SinumerikNCParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] SinumerikNCParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure([NotNull] SinumerikNCParser.ProcedureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParams([NotNull] SinumerikNCParser.ParamsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.paramOut"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamOut([NotNull] SinumerikNCParser.ParamOutContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] SinumerikNCParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] SinumerikNCParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] SinumerikNCParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.iterativeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterativeStatement([NotNull] SinumerikNCParser.IterativeStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJumpStatement([NotNull] SinumerikNCParser.JumpStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] SinumerikNCParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] SinumerikNCParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] SinumerikNCParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] SinumerikNCParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.binaryAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryAndExpression([NotNull] SinumerikNCParser.BinaryAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.binaryExclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryExclusiveOrExpression([NotNull] SinumerikNCParser.BinaryExclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.binaryInclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryInclusiveOrExpression([NotNull] SinumerikNCParser.BinaryInclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] SinumerikNCParser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusiveOrExpression([NotNull] SinumerikNCParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusiveOrExpression([NotNull] SinumerikNCParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.stringExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringExpression([NotNull] SinumerikNCParser.StringExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] SinumerikNCParser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] SinumerikNCParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] SinumerikNCParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] SinumerikNCParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.feedrate_override_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeedrate_override_path([NotNull] SinumerikNCParser.Feedrate_override_pathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.feedrate_override_rapid_traverse_velocity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeedrate_override_rapid_traverse_velocity([NotNull] SinumerikNCParser.Feedrate_override_rapid_traverse_velocityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.feedrate_override_position_or_spindle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeedrate_override_position_or_spindle([NotNull] SinumerikNCParser.Feedrate_override_position_or_spindleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.acceleration_compensation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAcceleration_compensation([NotNull] SinumerikNCParser.Acceleration_compensationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.feedrate_override_path_handwheel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeedrate_override_path_handwheel([NotNull] SinumerikNCParser.Feedrate_override_path_handwheelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.feedrate_override_axial_handwheel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeedrate_override_axial_handwheel([NotNull] SinumerikNCParser.Feedrate_override_axial_handwheelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.axis_spindle_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_spindle_identifier([NotNull] SinumerikNCParser.Axis_spindle_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.axis_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_identifier([NotNull] SinumerikNCParser.Axis_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.spindle_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpindle_identifier([NotNull] SinumerikNCParser.Spindle_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.axis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis([NotNull] SinumerikNCParser.AxisContext context);
}
