//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ..\..\antlr4-grammar\SinumerikNC.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SinumerikNCParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface ISinumerikNCVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] SinumerikNCParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.content"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContent([NotNull] SinumerikNCParser.ContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.declarationBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationBlock([NotNull] SinumerikNCParser.DeclarationBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] SinumerikNCParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.lineStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineStart([NotNull] SinumerikNCParser.LineStartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.blockNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockNumber([NotNull] SinumerikNCParser.BlockNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.labelDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabelDefinition([NotNull] SinumerikNCParser.LabelDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.procedureDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureDefinition([NotNull] SinumerikNCParser.ProcedureDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.procedureDefinitionHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureDefinitionHeader([NotNull] SinumerikNCParser.ProcedureDefinitionHeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.procedureModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureModifier([NotNull] SinumerikNCParser.ProcedureModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.parameterDefinitions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDefinitions([NotNull] SinumerikNCParser.ParameterDefinitionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.parameterDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDefinition([NotNull] SinumerikNCParser.ParameterDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.parameterDefinitionByValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDefinitionByValue([NotNull] SinumerikNCParser.ParameterDefinitionByValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.parameterDefinitionByReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDefinitionByReference([NotNull] SinumerikNCParser.ParameterDefinitionByReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] SinumerikNCParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.macroDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroDeclaration([NotNull] SinumerikNCParser.MacroDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.macroValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroValue([NotNull] SinumerikNCParser.MacroValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPath([NotNull] SinumerikNCParser.PathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.pathElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPathElements([NotNull] SinumerikNCParser.PathElementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.procedureDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedureDeclaration([NotNull] SinumerikNCParser.ProcedureDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.parameterDeclarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDeclarations([NotNull] SinumerikNCParser.ParameterDeclarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parameterDeclarationByValue</c>
	/// labeled alternative in <see cref="SinumerikNCParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDeclarationByValue([NotNull] SinumerikNCParser.ParameterDeclarationByValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>parameterDeclarationByReference</c>
	/// labeled alternative in <see cref="SinumerikNCParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDeclarationByReference([NotNull] SinumerikNCParser.ParameterDeclarationByReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.arrayDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayDeclaration([NotNull] SinumerikNCParser.ArrayDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] SinumerikNCParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.globalVariableModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobalVariableModifiers([NotNull] SinumerikNCParser.GlobalVariableModifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange([NotNull] SinumerikNCParser.RangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.preprocessingStop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreprocessingStop([NotNull] SinumerikNCParser.PreprocessingStopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.accessRights"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessRights([NotNull] SinumerikNCParser.AccessRightsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.accessDesignation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessDesignation([NotNull] SinumerikNCParser.AccessDesignationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.variableModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableModifiers([NotNull] SinumerikNCParser.VariableModifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.physicalUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPhysicalUnit([NotNull] SinumerikNCParser.PhysicalUnitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.limitValues"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLimitValues([NotNull] SinumerikNCParser.LimitValuesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.variableNameDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableNameDeclaration([NotNull] SinumerikNCParser.VariableNameDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.arrayDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayDefinition([NotNull] SinumerikNCParser.ArrayDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.variableAssignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableAssignmentExpression([NotNull] SinumerikNCParser.VariableAssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.arrayAssignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayAssignmentExpression([NotNull] SinumerikNCParser.ArrayAssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.variableRedecleration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableRedecleration([NotNull] SinumerikNCParser.VariableRedeclerationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>userVariableAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUserVariableAssignment([NotNull] SinumerikNCParser.UserVariableAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RParamAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRParamAssignment([NotNull] SinumerikNCParser.RParamAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SysVarAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSysVarAssignment([NotNull] SinumerikNCParser.SysVarAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arrayVariableAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayVariableAssignment([NotNull] SinumerikNCParser.ArrayVariableAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arrayRParamAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayRParamAssignment([NotNull] SinumerikNCParser.ArrayRParamAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>arraySysVarAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArraySysVarAssignment([NotNull] SinumerikNCParser.ArraySysVarAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] SinumerikNCParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] SinumerikNCParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] SinumerikNCParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseStatement([NotNull] SinumerikNCParser.CaseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.iterativeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterativeStatement([NotNull] SinumerikNCParser.IterativeStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.iterativeWhile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterativeWhile([NotNull] SinumerikNCParser.IterativeWhileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.iterativeFor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterativeFor([NotNull] SinumerikNCParser.IterativeForContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.iterativeRepeat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterativeRepeat([NotNull] SinumerikNCParser.IterativeRepeatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.iterativeLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterativeLoop([NotNull] SinumerikNCParser.IterativeLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJumpStatement([NotNull] SinumerikNCParser.JumpStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.gotoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotoStatement([NotNull] SinumerikNCParser.GotoStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.gotoCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotoCondition([NotNull] SinumerikNCParser.GotoConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>gotoLabel</c>
	/// labeled alternative in <see cref="SinumerikNCParser.gotoTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotoLabel([NotNull] SinumerikNCParser.GotoLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>gotoBlock</c>
	/// labeled alternative in <see cref="SinumerikNCParser.gotoTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGotoBlock([NotNull] SinumerikNCParser.GotoBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.callStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallStatement([NotNull] SinumerikNCParser.CallStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.syncActionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSyncActionStatement([NotNull] SinumerikNCParser.SyncActionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.syncActionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSyncActionId([NotNull] SinumerikNCParser.SyncActionIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.syncActionCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSyncActionCondition([NotNull] SinumerikNCParser.SyncActionConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.syncActionAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSyncActionAction([NotNull] SinumerikNCParser.SyncActionActionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>toStringExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitToStringExpression([NotNull] SinumerikNCParser.ToStringExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>additiveExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] SinumerikNCParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>inclusiveOrExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusiveOrExpression([NotNull] SinumerikNCParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>relationalExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] SinumerikNCParser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>multiplicativeExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] SinumerikNCParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>concatExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConcatExpression([NotNull] SinumerikNCParser.ConcatExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>primaryExpressionLabel</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpressionLabel([NotNull] SinumerikNCParser.PrimaryExpressionLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>andExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] SinumerikNCParser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binaryAndExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryAndExpression([NotNull] SinumerikNCParser.BinaryAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>exclusiveOrExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusiveOrExpression([NotNull] SinumerikNCParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binaryInclusiveOrExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryInclusiveOrExpression([NotNull] SinumerikNCParser.BinaryInclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>binaryExclusiveOrExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryExclusiveOrExpression([NotNull] SinumerikNCParser.BinaryExclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>unaryExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] SinumerikNCParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>signExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSignExpression([NotNull] SinumerikNCParser.SignExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>variableUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableUse([NotNull] SinumerikNCParser.VariableUseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>systemVariableUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSystemVariableUse([NotNull] SinumerikNCParser.SystemVariableUseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>rParamUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRParamUse([NotNull] SinumerikNCParser.RParamUseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>constantUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantUse([NotNull] SinumerikNCParser.ConstantUseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>functionUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionUse([NotNull] SinumerikNCParser.FunctionUseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>nestedExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNestedExpression([NotNull] SinumerikNCParser.NestedExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>macroUseLabel</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroUseLabel([NotNull] SinumerikNCParser.MacroUseLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>axisUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxisUse([NotNull] SinumerikNCParser.AxisUseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] SinumerikNCParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.numeric"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumeric([NotNull] SinumerikNCParser.NumericContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.macroUse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroUse([NotNull] SinumerikNCParser.MacroUseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] SinumerikNCParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.gCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGCode([NotNull] SinumerikNCParser.GCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.mCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMCode([NotNull] SinumerikNCParser.MCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.hCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHCode([NotNull] SinumerikNCParser.HCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.codeAssignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeAssignmentExpression([NotNull] SinumerikNCParser.CodeAssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.axisCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxisCode([NotNull] SinumerikNCParser.AxisCodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.axisAssignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxisAssignmentExpression([NotNull] SinumerikNCParser.AxisAssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.axis_spindle_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_spindle_identifier([NotNull] SinumerikNCParser.Axis_spindle_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.axis_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAxis_identifier([NotNull] SinumerikNCParser.Axis_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.spindle_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpindle_identifier([NotNull] SinumerikNCParser.Spindle_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.procedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProcedure([NotNull] SinumerikNCParser.ProcedureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.ownProcedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOwnProcedure([NotNull] SinumerikNCParser.OwnProcedureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameters([NotNull] SinumerikNCParser.ParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.predefinedProcedure"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPredefinedProcedure([NotNull] SinumerikNCParser.PredefinedProcedureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.acceleration_compensation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAcceleration_compensation([NotNull] SinumerikNCParser.Acceleration_compensationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.feedrate_override_path_handwheel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeedrate_override_path_handwheel([NotNull] SinumerikNCParser.Feedrate_override_path_handwheelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.feedrate_override_axial_handwheel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFeedrate_override_axial_handwheel([NotNull] SinumerikNCParser.Feedrate_override_axial_handwheelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] SinumerikNCParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.mathFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMathFunction([NotNull] SinumerikNCParser.MathFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.stringFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringFunction([NotNull] SinumerikNCParser.StringFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SinumerikNCParser.otherKeywords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOtherKeywords([NotNull] SinumerikNCParser.OtherKeywordsContext context);
}
