using LanceServer.Core.Document;
using LanceServer.Core.Symbol;

namespace LanceServer.Parser;

/// <summary>
/// Provides the interface to the parser generated by antlr
/// </summary>
public interface IParserManager
{
    /// <summary>
    /// Parses the provided document and returns the parse tree.
    /// </summary>
    /// <param name="document">The document to be parsed</param>
    /// <returns>The parse tree</returns>
    ParserResult Parse(PreprocessedDocument document);
    
    /// <summary>
    /// Visits the parse tree of the provided document to generate a list of all defined symbols
    /// </summary>
    /// <param name="document">The document to be visited</param>
    /// <returns>A list of all defined symbols</returns>
    IList<ISymbol> GetSymbolTableForDocument(ParsedDocument document);
    
    /// <summary>
    /// Visits the parse tree of the provided document to generate a list of all symbol uses
    /// </summary>
    /// <param name="document">The document to be visited</param>
    /// <returns>A list of all symbol uses</returns>
    IList<ISymbolUse> GetSymbolUseForDocument(SymbolisedDocument document);

    IList<LanguageToken> GetLanguageTokensForDocument(SymbolisedDocument document);
}