//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ..\..\antlr4-grammar\SinumerikNC.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISinumerikNCListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SinumerikNCBaseListener : ISinumerikNCListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] SinumerikNCParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] SinumerikNCParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContent([NotNull] SinumerikNCParser.ContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.content"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContent([NotNull] SinumerikNCParser.ContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.declarationScope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationScope([NotNull] SinumerikNCParser.DeclarationScopeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.declarationScope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationScope([NotNull] SinumerikNCParser.DeclarationScopeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.declarationBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationBlock([NotNull] SinumerikNCParser.DeclarationBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.declarationBlock"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationBlock([NotNull] SinumerikNCParser.DeclarationBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.scope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScope([NotNull] SinumerikNCParser.ScopeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.scope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScope([NotNull] SinumerikNCParser.ScopeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] SinumerikNCParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] SinumerikNCParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.lineStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLineStart([NotNull] SinumerikNCParser.LineStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.lineStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLineStart([NotNull] SinumerikNCParser.LineStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.blockNumberDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockNumberDefinition([NotNull] SinumerikNCParser.BlockNumberDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.blockNumberDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockNumberDefinition([NotNull] SinumerikNCParser.BlockNumberDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.blockNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlockNumber([NotNull] SinumerikNCParser.BlockNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.blockNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlockNumber([NotNull] SinumerikNCParser.BlockNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.labelDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabelDefinition([NotNull] SinumerikNCParser.LabelDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.labelDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabelDefinition([NotNull] SinumerikNCParser.LabelDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.procedureDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureDefinition([NotNull] SinumerikNCParser.ProcedureDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.procedureDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureDefinition([NotNull] SinumerikNCParser.ProcedureDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.procedureDefinitionHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureDefinitionHeader([NotNull] SinumerikNCParser.ProcedureDefinitionHeaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.procedureDefinitionHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureDefinitionHeader([NotNull] SinumerikNCParser.ProcedureDefinitionHeaderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.procedureModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureModifier([NotNull] SinumerikNCParser.ProcedureModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.procedureModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureModifier([NotNull] SinumerikNCParser.ProcedureModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.parameterDefinitions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDefinitions([NotNull] SinumerikNCParser.ParameterDefinitionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.parameterDefinitions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDefinitions([NotNull] SinumerikNCParser.ParameterDefinitionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.parameterDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDefinition([NotNull] SinumerikNCParser.ParameterDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.parameterDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDefinition([NotNull] SinumerikNCParser.ParameterDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.parameterDefinitionByValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDefinitionByValue([NotNull] SinumerikNCParser.ParameterDefinitionByValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.parameterDefinitionByValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDefinitionByValue([NotNull] SinumerikNCParser.ParameterDefinitionByValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.parameterDefinitionByReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDefinitionByReference([NotNull] SinumerikNCParser.ParameterDefinitionByReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.parameterDefinitionByReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDefinitionByReference([NotNull] SinumerikNCParser.ParameterDefinitionByReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] SinumerikNCParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] SinumerikNCParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.macroDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacroDeclaration([NotNull] SinumerikNCParser.MacroDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.macroDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacroDeclaration([NotNull] SinumerikNCParser.MacroDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.macroValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacroValue([NotNull] SinumerikNCParser.MacroValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.macroValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacroValue([NotNull] SinumerikNCParser.MacroValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.procedureDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureDeclaration([NotNull] SinumerikNCParser.ProcedureDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.procedureDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureDeclaration([NotNull] SinumerikNCParser.ProcedureDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.parameterDeclarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDeclarations([NotNull] SinumerikNCParser.ParameterDeclarationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.parameterDeclarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDeclarations([NotNull] SinumerikNCParser.ParameterDeclarationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>parameterDeclarationByValue</c>
	/// labeled alternative in <see cref="SinumerikNCParser.parameterDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDeclarationByValue([NotNull] SinumerikNCParser.ParameterDeclarationByValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>parameterDeclarationByValue</c>
	/// labeled alternative in <see cref="SinumerikNCParser.parameterDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDeclarationByValue([NotNull] SinumerikNCParser.ParameterDeclarationByValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>parameterDeclarationByReference</c>
	/// labeled alternative in <see cref="SinumerikNCParser.parameterDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterDeclarationByReference([NotNull] SinumerikNCParser.ParameterDeclarationByReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>parameterDeclarationByReference</c>
	/// labeled alternative in <see cref="SinumerikNCParser.parameterDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterDeclarationByReference([NotNull] SinumerikNCParser.ParameterDeclarationByReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.arrayDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayDeclaration([NotNull] SinumerikNCParser.ArrayDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.arrayDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayDeclaration([NotNull] SinumerikNCParser.ArrayDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] SinumerikNCParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] SinumerikNCParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.globalVariableModifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlobalVariableModifiers([NotNull] SinumerikNCParser.GlobalVariableModifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.globalVariableModifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlobalVariableModifiers([NotNull] SinumerikNCParser.GlobalVariableModifiersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange([NotNull] SinumerikNCParser.RangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange([NotNull] SinumerikNCParser.RangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.preprocessingStop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessingStop([NotNull] SinumerikNCParser.PreprocessingStopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.preprocessingStop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessingStop([NotNull] SinumerikNCParser.PreprocessingStopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.accessRights"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessRights([NotNull] SinumerikNCParser.AccessRightsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.accessRights"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessRights([NotNull] SinumerikNCParser.AccessRightsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.accessDesignation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessDesignation([NotNull] SinumerikNCParser.AccessDesignationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.accessDesignation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessDesignation([NotNull] SinumerikNCParser.AccessDesignationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.variableModifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableModifiers([NotNull] SinumerikNCParser.VariableModifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.variableModifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableModifiers([NotNull] SinumerikNCParser.VariableModifiersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.physicalUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPhysicalUnit([NotNull] SinumerikNCParser.PhysicalUnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.physicalUnit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPhysicalUnit([NotNull] SinumerikNCParser.PhysicalUnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.limitValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLimitValues([NotNull] SinumerikNCParser.LimitValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.limitValues"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLimitValues([NotNull] SinumerikNCParser.LimitValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.variableNameDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableNameDeclaration([NotNull] SinumerikNCParser.VariableNameDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.variableNameDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableNameDeclaration([NotNull] SinumerikNCParser.VariableNameDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.arrayDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayDefinition([NotNull] SinumerikNCParser.ArrayDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.arrayDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayDefinition([NotNull] SinumerikNCParser.ArrayDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.variableAssignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableAssignmentExpression([NotNull] SinumerikNCParser.VariableAssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.variableAssignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableAssignmentExpression([NotNull] SinumerikNCParser.VariableAssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.arrayAssignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayAssignmentExpression([NotNull] SinumerikNCParser.ArrayAssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.arrayAssignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayAssignmentExpression([NotNull] SinumerikNCParser.ArrayAssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.variableRedecleration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableRedecleration([NotNull] SinumerikNCParser.VariableRedeclerationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.variableRedecleration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableRedecleration([NotNull] SinumerikNCParser.VariableRedeclerationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>userVariableAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUserVariableAssignment([NotNull] SinumerikNCParser.UserVariableAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>userVariableAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUserVariableAssignment([NotNull] SinumerikNCParser.UserVariableAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>RParamAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRParamAssignment([NotNull] SinumerikNCParser.RParamAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>RParamAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRParamAssignment([NotNull] SinumerikNCParser.RParamAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SysVarAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSysVarAssignment([NotNull] SinumerikNCParser.SysVarAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SysVarAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSysVarAssignment([NotNull] SinumerikNCParser.SysVarAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>arrayVariableAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayVariableAssignment([NotNull] SinumerikNCParser.ArrayVariableAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>arrayVariableAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayVariableAssignment([NotNull] SinumerikNCParser.ArrayVariableAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>arrayRParamAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayRParamAssignment([NotNull] SinumerikNCParser.ArrayRParamAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>arrayRParamAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayRParamAssignment([NotNull] SinumerikNCParser.ArrayRParamAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>arraySysVarAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArraySysVarAssignment([NotNull] SinumerikNCParser.ArraySysVarAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>arraySysVarAssignment</c>
	/// labeled alternative in <see cref="SinumerikNCParser.variableAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArraySysVarAssignment([NotNull] SinumerikNCParser.ArraySysVarAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] SinumerikNCParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] SinumerikNCParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] SinumerikNCParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] SinumerikNCParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] SinumerikNCParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] SinumerikNCParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.ifStatementElse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatementElse([NotNull] SinumerikNCParser.IfStatementElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.ifStatementElse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatementElse([NotNull] SinumerikNCParser.IfStatementElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.caseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseStatement([NotNull] SinumerikNCParser.CaseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.caseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseStatement([NotNull] SinumerikNCParser.CaseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.iterativeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIterativeStatement([NotNull] SinumerikNCParser.IterativeStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.iterativeStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIterativeStatement([NotNull] SinumerikNCParser.IterativeStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.iterativeWhile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIterativeWhile([NotNull] SinumerikNCParser.IterativeWhileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.iterativeWhile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIterativeWhile([NotNull] SinumerikNCParser.IterativeWhileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.iterativeFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIterativeFor([NotNull] SinumerikNCParser.IterativeForContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.iterativeFor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIterativeFor([NotNull] SinumerikNCParser.IterativeForContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.iterativeRepeat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIterativeRepeat([NotNull] SinumerikNCParser.IterativeRepeatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.iterativeRepeat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIterativeRepeat([NotNull] SinumerikNCParser.IterativeRepeatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.iterativeLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIterativeLoop([NotNull] SinumerikNCParser.IterativeLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.iterativeLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIterativeLoop([NotNull] SinumerikNCParser.IterativeLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.jumpStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJumpStatement([NotNull] SinumerikNCParser.JumpStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.jumpStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJumpStatement([NotNull] SinumerikNCParser.JumpStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.gotoStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotoStatement([NotNull] SinumerikNCParser.GotoStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.gotoStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotoStatement([NotNull] SinumerikNCParser.GotoStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>gotoLabel</c>
	/// labeled alternative in <see cref="SinumerikNCParser.gotoTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotoLabel([NotNull] SinumerikNCParser.GotoLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>gotoLabel</c>
	/// labeled alternative in <see cref="SinumerikNCParser.gotoTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotoLabel([NotNull] SinumerikNCParser.GotoLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>gotoBlock</c>
	/// labeled alternative in <see cref="SinumerikNCParser.gotoTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotoBlock([NotNull] SinumerikNCParser.GotoBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>gotoBlock</c>
	/// labeled alternative in <see cref="SinumerikNCParser.gotoTarget"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotoBlock([NotNull] SinumerikNCParser.GotoBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>call</c>
	/// labeled alternative in <see cref="SinumerikNCParser.callStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] SinumerikNCParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>call</c>
	/// labeled alternative in <see cref="SinumerikNCParser.callStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] SinumerikNCParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>procedureCall</c>
	/// labeled alternative in <see cref="SinumerikNCParser.callStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureCall([NotNull] SinumerikNCParser.ProcedureCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>procedureCall</c>
	/// labeled alternative in <see cref="SinumerikNCParser.callStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureCall([NotNull] SinumerikNCParser.ProcedureCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>externalCall</c>
	/// labeled alternative in <see cref="SinumerikNCParser.callStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExternalCall([NotNull] SinumerikNCParser.ExternalCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>externalCall</c>
	/// labeled alternative in <see cref="SinumerikNCParser.callStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExternalCall([NotNull] SinumerikNCParser.ExternalCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>callPath</c>
	/// labeled alternative in <see cref="SinumerikNCParser.callStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallPath([NotNull] SinumerikNCParser.CallPathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>callPath</c>
	/// labeled alternative in <see cref="SinumerikNCParser.callStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallPath([NotNull] SinumerikNCParser.CallPathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>modalCall</c>
	/// labeled alternative in <see cref="SinumerikNCParser.callStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterModalCall([NotNull] SinumerikNCParser.ModalCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>modalCall</c>
	/// labeled alternative in <see cref="SinumerikNCParser.callStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitModalCall([NotNull] SinumerikNCParser.ModalCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] SinumerikNCParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] SinumerikNCParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.syncActionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyncActionStatement([NotNull] SinumerikNCParser.SyncActionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.syncActionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyncActionStatement([NotNull] SinumerikNCParser.SyncActionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.syncActionId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyncActionId([NotNull] SinumerikNCParser.SyncActionIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.syncActionId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyncActionId([NotNull] SinumerikNCParser.SyncActionIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.syncActionCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyncActionCondition([NotNull] SinumerikNCParser.SyncActionConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.syncActionCondition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyncActionCondition([NotNull] SinumerikNCParser.SyncActionConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.syncActionAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSyncActionAction([NotNull] SinumerikNCParser.SyncActionActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.syncActionAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSyncActionAction([NotNull] SinumerikNCParser.SyncActionActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>toStringExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterToStringExpression([NotNull] SinumerikNCParser.ToStringExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>toStringExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitToStringExpression([NotNull] SinumerikNCParser.ToStringExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>additiveExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveExpression([NotNull] SinumerikNCParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>additiveExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveExpression([NotNull] SinumerikNCParser.AdditiveExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>inclusiveOrExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInclusiveOrExpression([NotNull] SinumerikNCParser.InclusiveOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>inclusiveOrExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInclusiveOrExpression([NotNull] SinumerikNCParser.InclusiveOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>relationalExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] SinumerikNCParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>relationalExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] SinumerikNCParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>multiplicativeExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeExpression([NotNull] SinumerikNCParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>multiplicativeExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeExpression([NotNull] SinumerikNCParser.MultiplicativeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>concatExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConcatExpression([NotNull] SinumerikNCParser.ConcatExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>concatExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConcatExpression([NotNull] SinumerikNCParser.ConcatExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>primaryExpressionLabel</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpressionLabel([NotNull] SinumerikNCParser.PrimaryExpressionLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>primaryExpressionLabel</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpressionLabel([NotNull] SinumerikNCParser.PrimaryExpressionLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>andExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpression([NotNull] SinumerikNCParser.AndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>andExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpression([NotNull] SinumerikNCParser.AndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>binaryAndExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryAndExpression([NotNull] SinumerikNCParser.BinaryAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>binaryAndExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryAndExpression([NotNull] SinumerikNCParser.BinaryAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>exclusiveOrExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExclusiveOrExpression([NotNull] SinumerikNCParser.ExclusiveOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>exclusiveOrExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExclusiveOrExpression([NotNull] SinumerikNCParser.ExclusiveOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>binaryInclusiveOrExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryInclusiveOrExpression([NotNull] SinumerikNCParser.BinaryInclusiveOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>binaryInclusiveOrExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryInclusiveOrExpression([NotNull] SinumerikNCParser.BinaryInclusiveOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>binaryExclusiveOrExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryExclusiveOrExpression([NotNull] SinumerikNCParser.BinaryExclusiveOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>binaryExclusiveOrExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryExclusiveOrExpression([NotNull] SinumerikNCParser.BinaryExclusiveOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpression([NotNull] SinumerikNCParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpression([NotNull] SinumerikNCParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>signExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSignExpression([NotNull] SinumerikNCParser.SignExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>signExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSignExpression([NotNull] SinumerikNCParser.SignExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>variableUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableUse([NotNull] SinumerikNCParser.VariableUseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>variableUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableUse([NotNull] SinumerikNCParser.VariableUseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>systemVariableUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSystemVariableUse([NotNull] SinumerikNCParser.SystemVariableUseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>systemVariableUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSystemVariableUse([NotNull] SinumerikNCParser.SystemVariableUseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>rParamUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRParamUse([NotNull] SinumerikNCParser.RParamUseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>rParamUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRParamUse([NotNull] SinumerikNCParser.RParamUseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>constantUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantUse([NotNull] SinumerikNCParser.ConstantUseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>constantUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantUse([NotNull] SinumerikNCParser.ConstantUseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>functionUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionUse([NotNull] SinumerikNCParser.FunctionUseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>functionUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionUse([NotNull] SinumerikNCParser.FunctionUseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>nestedExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNestedExpression([NotNull] SinumerikNCParser.NestedExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>nestedExpression</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNestedExpression([NotNull] SinumerikNCParser.NestedExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>axisUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAxisUse([NotNull] SinumerikNCParser.AxisUseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>axisUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAxisUse([NotNull] SinumerikNCParser.AxisUseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>pathUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathUse([NotNull] SinumerikNCParser.PathUseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>pathUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathUse([NotNull] SinumerikNCParser.PathUseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>macroUseLabel</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacroUseLabel([NotNull] SinumerikNCParser.MacroUseLabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>macroUseLabel</c>
	/// labeled alternative in <see cref="SinumerikNCParser.primaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacroUseLabel([NotNull] SinumerikNCParser.MacroUseLabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.rParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRParam([NotNull] SinumerikNCParser.RParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.rParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRParam([NotNull] SinumerikNCParser.RParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] SinumerikNCParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] SinumerikNCParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.numeric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumeric([NotNull] SinumerikNCParser.NumericContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.numeric"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumeric([NotNull] SinumerikNCParser.NumericContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.intUnsigned"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntUnsigned([NotNull] SinumerikNCParser.IntUnsignedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.intUnsigned"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntUnsigned([NotNull] SinumerikNCParser.IntUnsignedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.realUnsigned"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRealUnsigned([NotNull] SinumerikNCParser.RealUnsignedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.realUnsigned"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRealUnsigned([NotNull] SinumerikNCParser.RealUnsignedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.macroUse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacroUse([NotNull] SinumerikNCParser.MacroUseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.macroUse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacroUse([NotNull] SinumerikNCParser.MacroUseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPath([NotNull] SinumerikNCParser.PathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPath([NotNull] SinumerikNCParser.PathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.pathElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPathElements([NotNull] SinumerikNCParser.PathElementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.pathElements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPathElements([NotNull] SinumerikNCParser.PathElementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] SinumerikNCParser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] SinumerikNCParser.CommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.gCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGCode([NotNull] SinumerikNCParser.GCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.gCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGCode([NotNull] SinumerikNCParser.GCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.hCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHCode([NotNull] SinumerikNCParser.HCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.hCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHCode([NotNull] SinumerikNCParser.HCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.mCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMCode([NotNull] SinumerikNCParser.MCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.mCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMCode([NotNull] SinumerikNCParser.MCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.codeAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeAssignment([NotNull] SinumerikNCParser.CodeAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.codeAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeAssignment([NotNull] SinumerikNCParser.CodeAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.codeAssignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeAssignmentExpression([NotNull] SinumerikNCParser.CodeAssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.codeAssignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeAssignmentExpression([NotNull] SinumerikNCParser.CodeAssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.codeAssignmentParameterized"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeAssignmentParameterized([NotNull] SinumerikNCParser.CodeAssignmentParameterizedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.codeAssignmentParameterized"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeAssignmentParameterized([NotNull] SinumerikNCParser.CodeAssignmentParameterizedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.commandParameterAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandParameterAssignment([NotNull] SinumerikNCParser.CommandParameterAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.commandParameterAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandParameterAssignment([NotNull] SinumerikNCParser.CommandParameterAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.spindleSpeed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpindleSpeed([NotNull] SinumerikNCParser.SpindleSpeedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.spindleSpeed"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpindleSpeed([NotNull] SinumerikNCParser.SpindleSpeedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.speedAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpeedAssignment([NotNull] SinumerikNCParser.SpeedAssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.speedAssignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpeedAssignment([NotNull] SinumerikNCParser.SpeedAssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.speedAssignmentParameterized"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpeedAssignmentParameterized([NotNull] SinumerikNCParser.SpeedAssignmentParameterizedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.speedAssignmentParameterized"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpeedAssignmentParameterized([NotNull] SinumerikNCParser.SpeedAssignmentParameterizedContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.axisCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAxisCode([NotNull] SinumerikNCParser.AxisCodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.axisCode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAxisCode([NotNull] SinumerikNCParser.AxisCodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.axisAssignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAxisAssignmentExpression([NotNull] SinumerikNCParser.AxisAssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.axisAssignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAxisAssignmentExpression([NotNull] SinumerikNCParser.AxisAssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.axis_spindle_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAxis_spindle_identifier([NotNull] SinumerikNCParser.Axis_spindle_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.axis_spindle_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAxis_spindle_identifier([NotNull] SinumerikNCParser.Axis_spindle_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.axis_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAxis_identifier([NotNull] SinumerikNCParser.Axis_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.axis_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAxis_identifier([NotNull] SinumerikNCParser.Axis_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.spindle_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpindle_identifier([NotNull] SinumerikNCParser.Spindle_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.spindle_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpindle_identifier([NotNull] SinumerikNCParser.Spindle_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>predefinedProcedureUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.procedure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredefinedProcedureUse([NotNull] SinumerikNCParser.PredefinedProcedureUseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>predefinedProcedureUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.procedure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredefinedProcedureUse([NotNull] SinumerikNCParser.PredefinedProcedureUseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ownProcedureUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.procedure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOwnProcedureUse([NotNull] SinumerikNCParser.OwnProcedureUseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ownProcedureUse</c>
	/// labeled alternative in <see cref="SinumerikNCParser.procedure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOwnProcedureUse([NotNull] SinumerikNCParser.OwnProcedureUseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.ownProcedure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOwnProcedure([NotNull] SinumerikNCParser.OwnProcedureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.ownProcedure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOwnProcedure([NotNull] SinumerikNCParser.OwnProcedureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameters([NotNull] SinumerikNCParser.ParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameters([NotNull] SinumerikNCParser.ParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.predefinedProcedure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredefinedProcedure([NotNull] SinumerikNCParser.PredefinedProcedureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.predefinedProcedure"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredefinedProcedure([NotNull] SinumerikNCParser.PredefinedProcedureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] SinumerikNCParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] SinumerikNCParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.mathFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMathFunction([NotNull] SinumerikNCParser.MathFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.mathFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMathFunction([NotNull] SinumerikNCParser.MathFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.stringFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringFunction([NotNull] SinumerikNCParser.StringFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.stringFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringFunction([NotNull] SinumerikNCParser.StringFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKeyword([NotNull] SinumerikNCParser.KeywordContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.keyword"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKeyword([NotNull] SinumerikNCParser.KeywordContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.cpon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCpon([NotNull] SinumerikNCParser.CponContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.cpon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCpon([NotNull] SinumerikNCParser.CponContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.cpof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCpof([NotNull] SinumerikNCParser.CpofContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.cpof"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCpof([NotNull] SinumerikNCParser.CpofContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.cplpos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCplpos([NotNull] SinumerikNCParser.CplposContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.cplpos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCplpos([NotNull] SinumerikNCParser.CplposContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SinumerikNCParser.cpfpos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCpfpos([NotNull] SinumerikNCParser.CpfposContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SinumerikNCParser.cpfpos"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCpfpos([NotNull] SinumerikNCParser.CpfposContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
